set client_min_messages = WARNING;
alter table if exists cita_servicios drop constraint if exists FK1bopji12796dyd9egdylg828i;
alter table if exists cita_servicios drop constraint if exists FK5lpsx6uey11rebxy3ghf7m9os;
alter table if exists citas drop constraint if exists FKpuiuwn6ymwdm1tw8lcy0rbyrd;
alter table if exists citas drop constraint if exists FKcitrr49x1d6tcxpajkj7yj1mm;
alter table if exists citas drop constraint if exists FKqmf1ou56bls8snaow1orq8yj0;
alter table if exists detalle_pagos drop constraint if exists FKf01qx7mkwtuljm2qgmyd44t0g;
alter table if exists detalle_pagos drop constraint if exists FKms1rm23y82aq3qcp7kj550ltt;
alter table if exists detalles drop constraint if exists FKio4oyl8qt5jclekxp7bwws2iy;
alter table if exists detalles drop constraint if exists FKrhu623d1b3926ilbyu5ajhvdk;
alter table if exists detalles drop constraint if exists FK1m8k69y1b3rs71rkahctgs9v5;
alter table if exists excepciones_horarios drop constraint if exists FKj42u68alnk89t74x5yi1wn43i;
alter table if exists horario_barberos drop constraint if exists FKhwb5tc6xyt551ac0d0ir69pbm;
alter table if exists movimiento_inventarios drop constraint if exists FKa9sd6fl88v6ixrt3u15j1091o;
alter table if exists movimiento_inventarios drop constraint if exists FKo66743bmi08t96338jwqs9np6;
alter table if exists ventas drop constraint if exists FKor45og8y75lbcbhns93614j6g;
alter table if exists ventas drop constraint if exists FKthulohjpvy8wadut9tduutq7v;
alter table if exists ventas drop constraint if exists FKco9r9xjcdqtgd4nvnnolsr6ei;
drop table if exists cita_servicios cascade;
drop table if exists citas cascade;
drop table if exists detalle_pagos cascade;
drop table if exists detalles cascade;
drop table if exists excepciones_horarios cascade;
drop table if exists horario_barberos cascade;
drop table if exists movimiento_inventarios cascade;
drop table if exists productos cascade;
drop table if exists servicios cascade;
drop table if exists tipo_pagos cascade;
drop table if exists usuarios cascade;
drop table if exists ventas cascade;
