--create table cita_servicios (precio_cobrado numeric(10,2), cita_id bigint, id bigint generated by default as identity, servicio_id bigint, primary key (id));
--create table citas (pago_inicial numeric(10,2), barbero_id bigint, cliente_id bigint, fecha_hora_fin timestamp(6), fecha_hora_inicio timestamp(6), id bigint generated by default as identity, tipo_pago_id bigint, estado varchar(255), primary key (id));
--create table detalle_pagos (monto numeric(10,2), id bigint generated by default as identity, tipo_pago_id bigint, venta_id bigint, metodo_pago varchar(255) not null, primary key (id));
--create table detalles (cantidad integer not null, precio_unitario float(53) not null, id bigint generated by default as identity, producto_id bigint, servicio_id bigint, venta_id bigint, primary key (id));
--create table excepciones_horarios (es_disponible boolean not null, fecha DATE DEFAULT CURRENT_DATE, hora_fin time(6), hora_inicio time(6), deleted_at timestamp(6) with time zone, id bigint generated by default as identity, usuario_id bigint, primary key (id));
--create table horario_barberos (hora_fin time(6), hora_inicio time(6), id bigint generated by default as identity, usuario_id bigint, dia_semana varchar(255), primary key (id));
--create table movimiento_inventarios (cantidad integer not null, fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id bigint generated by default as identity, producto_id bigint, usuario_id bigint, motivo varchar(255) not null, tipo_movimiento varchar(255) not null, primary key (id));
--create table productos (precio_venta numeric(10,2), stock_actual integer not null, stock_minimo integer not null, id bigint generated by default as identity, descripcion TEXT, nombre varchar(255), primary key (id));
--create table servicios (duracion_estimada integer not null, precio numeric(12,2), id bigint generated by default as identity, descripcion TEXT, nombre varchar(255), primary key (id));
--create table tipo_pagos (id bigint generated by default as identity, nombre varchar(255), primary key (id));
--create table usuarios (fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id bigint generated by default as identity, apellido varchar(255), email varchar(255) not null unique, nombre varchar(255), password varchar(255), rol varchar(255), telefono varchar(255), primary key (id));
--create table ventas (monto_total numeric(10,2), cita_id bigint unique, cliente_id bigint, fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id bigint generated by default as identity, usuario_id bigint, estado_pago varchar(255) not null, tipo_pago varchar(255) not null, primary key (id));
--alter table if exists cita_servicios add constraint FK1bopji12796dyd9egdylg828i foreign key (cita_id) references citas;
--alter table if exists cita_servicios add constraint FK5lpsx6uey11rebxy3ghf7m9os foreign key (servicio_id) references servicios;
--alter table if exists citas add constraint FKpuiuwn6ymwdm1tw8lcy0rbyrd foreign key (barbero_id) references usuarios;
--alter table if exists citas add constraint FKcitrr49x1d6tcxpajkj7yj1mm foreign key (cliente_id) references usuarios;
--alter table if exists citas add constraint FKqmf1ou56bls8snaow1orq8yj0 foreign key (tipo_pago_id) references tipo_pagos;
--alter table if exists detalle_pagos add constraint FKf01qx7mkwtuljm2qgmyd44t0g foreign key (tipo_pago_id) references tipo_pagos;
--alter table if exists detalle_pagos add constraint FKms1rm23y82aq3qcp7kj550ltt foreign key (venta_id) references ventas;
--alter table if exists detalles add constraint FKio4oyl8qt5jclekxp7bwws2iy foreign key (producto_id) references productos;
--alter table if exists detalles add constraint FKrhu623d1b3926ilbyu5ajhvdk foreign key (servicio_id) references servicios;
--alter table if exists detalles add constraint FK1m8k69y1b3rs71rkahctgs9v5 foreign key (venta_id) references ventas;
--alter table if exists excepciones_horarios add constraint FKj42u68alnk89t74x5yi1wn43i foreign key (usuario_id) references usuarios;
--alter table if exists horario_barberos add constraint FKhwb5tc6xyt551ac0d0ir69pbm foreign key (usuario_id) references usuarios;
--alter table if exists movimiento_inventarios add constraint FKa9sd6fl88v6ixrt3u15j1091o foreign key (producto_id) references productos;
--alter table if exists movimiento_inventarios add constraint FKo66743bmi08t96338jwqs9np6 foreign key (usuario_id) references usuarios;
--alter table if exists ventas add constraint FKor45og8y75lbcbhns93614j6g foreign key (cita_id) references citas;
--alter table if exists ventas add constraint FKthulohjpvy8wadut9tduutq7v foreign key (cliente_id) references usuarios;
--alter table if exists ventas add constraint FKco9r9xjcdqtgd4nvnnolsr6ei foreign key (usuario_id) references usuarios;



-- ===== TABLAS PRINCIPALES =====

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    apellido VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    telefono VARCHAR(255),
    rol VARCHAR(255),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tipo_pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255)
);

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    descripcion TEXT,
    precio_venta NUMERIC(10,2),
    stock_minimo INTEGER NOT NULL,
    stock_actual INTEGER NOT NULL
);

CREATE TABLE servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    descripcion TEXT,
    duracion_estimada INTEGER NOT NULL,
    precio NUMERIC(12,2)
);

CREATE TABLE citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbero_id BIGINT,
    cliente_id BIGINT,
    tipo_pago_id BIGINT,
    pago_inicial NUMERIC(10,2),
    fecha_hora_inicio TIMESTAMP(6),
    fecha_hora_fin TIMESTAMP(6),
    estado VARCHAR(255)
);

CREATE TABLE cita_servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT,
    servicio_id BIGINT,
    precio_cobrado NUMERIC(10,2)
);

CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT UNIQUE,
    cliente_id BIGINT,
    usuario_id BIGINT,
    monto_total NUMERIC(10,2),
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_pago VARCHAR(255) NOT NULL,
    tipo_pago VARCHAR(255) NOT NULL
);

CREATE TABLE detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT,
    servicio_id BIGINT,
    venta_id BIGINT,
    cantidad INTEGER NOT NULL,
    precio_unitario FLOAT(53) NOT NULL
);

CREATE TABLE detalle_pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_pago_id BIGINT,
    venta_id BIGINT,
    metodo_pago VARCHAR(255) NOT NULL,
    monto NUMERIC(10,2)
);

CREATE TABLE movimiento_inventarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT,
    usuario_id BIGINT,
    cantidad INTEGER NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    tipo_movimiento VARCHAR(255) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE horario_barberos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    dia_semana VARCHAR(255),
    hora_inicio TIME(6),
    hora_fin TIME(6)
);

CREATE TABLE excepciones_horarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    es_disponible BOOLEAN NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    hora_inicio TIME(6),
    hora_fin TIME(6),
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

-- Relaciones=====

ALTER TABLE cita_servicios
    ADD CONSTRAINT fk_cita_serv FOREIGN KEY (cita_id) REFERENCES citas,
    ADD CONSTRAINT fk_servicio FOREIGN KEY (servicio_id) REFERENCES servicios;

ALTER TABLE citas
    ADD CONSTRAINT fk_barbero FOREIGN KEY (barbero_id) REFERENCES usuarios,
    ADD CONSTRAINT fk_cliente FOREIGN KEY (cliente_id) REFERENCES usuarios,
    ADD CONSTRAINT fk_tipo_pago FOREIGN KEY (tipo_pago_id) REFERENCES tipo_pagos;

ALTER TABLE detalle_pagos
    ADD CONSTRAINT fk_pago_tipo FOREIGN KEY (tipo_pago_id) REFERENCES tipo_pagos,
    ADD CONSTRAINT fk_pago_venta FOREIGN KEY (venta_id) REFERENCES ventas;

ALTER TABLE detalles
    ADD CONSTRAINT fk_det_producto FOREIGN KEY (producto_id) REFERENCES productos,
    ADD CONSTRAINT fk_det_servicio FOREIGN KEY (servicio_id) REFERENCES servicios,
    ADD CONSTRAINT fk_det_venta FOREIGN KEY (venta_id) REFERENCES ventas;

ALTER TABLE excepciones_horarios
    ADD CONSTRAINT fk_excep_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios;

ALTER TABLE horario_barberos
    ADD CONSTRAINT fk_horario_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios;

ALTER TABLE movimiento_inventarios
    ADD CONSTRAINT fk_mov_producto FOREIGN KEY (producto_id) REFERENCES productos,
    ADD CONSTRAINT fk_mov_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios;

ALTER TABLE ventas
    ADD CONSTRAINT fk_venta_cita FOREIGN KEY (cita_id) REFERENCES citas,
    ADD CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_id) REFERENCES usuarios,
    ADD CONSTRAINT fk_venta_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios;

-- ================================================
-- FIN DEL SCHEMA
-- ================================================
